### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by alrighttheresham** [sindresorhus/infer-bin#2] opened 2015-09-10 16:42 UTC
node installed via homebrew 

➜  ~  node -v
v0.12.7
➜  ~  npm -v
3.3.2
➜  ~

➜  ~  sudo npm install --global infer-bin
/usr/local/bin/infer -> /usr/local/lib/node_modules/infer-bin/cli.js

> spawn-sync@1.0.13 postinstall /usr/local/lib/node_modules/infer-bin/node_modules/spawn-sync
> node postinstall
> 
> spawn-sync@1.0.13 postinstall /usr/local/lib/node_modules/infer-bin/node_modules/spawn-sync
> node postinstall
> 
> infer-bin@0.1.1 postinstall /usr/local/lib/node_modules/infer-bin
> node lib/install.js

/usr/local/lib/node_modules/infer-bin/lib/index.js:36
                throw err;
                      ^
Error: spawn tar ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--global" "infer-bin"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.2
npm ERR! code ELIFECYCLE

npm ERR! infer-bin@0.1.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the infer-bin@0.1.1 postinstall script 'node lib/install.js'.
npm ERR! This is most likely a problem with the infer-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls infer-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/damianoneill/npm-debug.log
➜  ~

**Comment by arthurvr** [comment] 2015-10-04 16:33
Seems like a dupe of #1.

**Closed as completed by arthurvr** 2015-10-04 16:33 UTC
